version: "3"

services:
  redis:
    image: redis:3.2.12
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./redis/data:/data"
    container_name: redis3.2

  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    container_name: mysql5.7

  nginx-php:
    image: registry.cn-hangzhou.aliyuncs.com/zgang/nginx-php-fpm:1.5.6
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/sites-enabled:/etc/nginx/sites-enabled"
      - "./www:/var/www"
      - "./log/nginx:/var/log/nginx"
    container_name: nginx-php7.2
    # links:
    #   - redis
    #   - mysql
    working_dir: /var/www 
